In [2]:
import numpy as np
a = np.array([1,2,3,4])
sum(a)

10

In [9]:
a = np.reshape(a,(2,2))
print(sum(a))
np.sum(a*a,axis=1)

[4 6]


array([ 5, 25])

In [29]:
np.maximum(a,a)
b = np.array([1,1])
b.shape
c = np.tile(b,(2,2))
print(c.shape)
type(c)

(2, 4)


numpy.ndarray

In [4]:
print(np.mean(a,axis =0))

[2. 3.]


In [5]:
print(a[1])

[3 4]


In [6]:
da = np.gradient(a)
print(da)

[array([[2., 2.],
       [2., 2.]]), array([[1., 1.],
       [1., 1.]])]


In [14]:
a = np.array([1,2,3,4])
y = a**2
da = np.gradient(y,edge_order = 1)
print(da)

[3. 4. 6. 7.]


In [16]:
help(np.gradient)

Help on function gradient in module numpy:

gradient(f, *varargs, axis=None, edge_order=1)
    Return the gradient of an N-dimensional array.
    
    The gradient is computed using second order accurate central differences
    in the interior points and either first or second order accurate one-sides
    (forward or backwards) differences at the boundaries.
    The returned gradient hence has the same shape as the input array.
    
    Parameters
    ----------
    f : array_like
        An N-dimensional array containing samples of a scalar function.
    varargs : list of scalar or array, optional
        Spacing between f values. Default unitary spacing for all dimensions.
        Spacing can be specified using:
    
        1. single scalar to specify a sample distance for all dimensions.
        2. N scalars to specify a constant sample distance for each dimension.
           i.e. `dx`, `dy`, `dz`, ...
        3. N arrays to specify the coordinates of the values along each
        

In [30]:
a = np.array([[1,2],[3,4]])

In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
a[1,1]

4

In [36]:
a[[1,1],[1,0]]

array([4, 3])

In [38]:
np.arange(3)

array([0, 1, 2])

In [39]:
a+1

array([[2, 3],
       [4, 5]])

In [41]:
np.maximum(a+1,0)

array([[2, 3],
       [4, 5]])

In [44]:
print(a)
a.sum(1)

[[1 2]
 [3 4]]


array([3, 7])

In [47]:
import randan

ModuleNotFoundError: No module named 'randan'

In [49]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [54]:
index = np.sort(np.random.choice(5,3,False))
print(index)

[0 3 4]


In [56]:
a
print(a[1])

[3 4]


In [64]:
np.max(a,1)

array([2, 4])

In [70]:
dict = {}
dict['a'] = 3
print(dict)

{'a': 3}


In [71]:
range(2)

range(0, 2)

In [72]:
for i in range(2):
    print(i)

0
1


In [3]:
import numpy as np
a = [1,3,4,5]
b = np.exp(a)
print(b)

[  2.71828183  20.08553692  54.59815003 148.4131591 ]


In [5]:
np.arange(2)

array([0, 1])

In [7]:
b = np.reshape(a,(2,2))

In [10]:
print(b)
print(np.sum(b,axis=1))

[[1 3]
 [4 5]]
[4 9]


In [13]:
print(np.newaxis)
type(np.newaxis)

None


NoneType

In [17]:
import numpy as np
a = np.array([1,2,3])
b = np.tile(a.T,(3,1))
print(b)
print(b+a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[2 4 6]
 [2 4 6]
 [2 4 6]]
